Repository MIT-Emerging-Talent/ET6-CDSP-group-24-repo, pull requests merged in 2025-06, with the labels that each got.

#8 Add group norms
  collaboration/README.md
Labels: documentation

#14 Main readme - milestone 0
  README.md
Labels: documentation

#15 Add Milestone 0 Retrospective
  collaboration/retrospective.md
Labels: documentation

#12 Communication
  collaboration/communication.md
Labels: documentation

#17 Learning goals
  collaboration/learning_goals.md
Labels: documentation

#21 update on the communication file
  collaboration/communication.md
Labels: documentation

#24 Sync Upstream Changes into main
  .github/workflows/ci-checks.yml
  1_datasets/guide.md
  collaboration/guide/0_repository_setup.md
  collaboration/retrospectives/0_cross_cultural_collaboration.md
  collaboration/retrospectives/1_problem_identification.md
  collaboration/retrospectives/2_data_collection.md
  collaboration/retrospectives/3_data_analysis.md
  collaboration/retrospectives/4_communicating_results.md
  collaboration/retrospectives/5_final_presentation.md
  collaboration/retrospectives/README.md
  collaboration/retrospectives/_template.md
  guide.md
Labels: sync

#29 Meetings
  collaboration/meeting_minutes/meeting_01
  collaboration/meeting_minutes/meeting_02
  collaboration/meeting_minutes/meeting_03
Labels: documentation, enhancement

#34 Meetings
  collaboration/meeting_minutes/meeting_01
  collaboration/meeting_minutes/meeting_02
  collaboration/meeting_minutes/meeting_04
Labels: documentation, enhancement

#42 add meeting 6 min
  collaboration/meeting_minutes/milestone_1_06_11_meeting_06.md
Labels: documentation

#40 Fix: Markdown Formatting in Meeting Minutes
  collaboration/meeting_minutes/milestone_0_05_29_meeting_01.md
  collaboration/meeting_minutes/milestone_0_06_03_meeting_02.md
  collaboration/meeting_minutes/milestone_1_06_08_meeting_04.md
  collaboration/meeting_minutes/milestone_1_06_10_meeting_05.md
Labels: documentation

#47 Add Meeting #08 minutes
  collaboration/meeting_minutes/milestone_1_06_13_meeting_08.md
Labels: documentation

#51 preparing the minutes meeting #7
  collaboration/meeting_minutes/milestone_1_06_12_meeting_07.md
Labels: documentation

#60 Add Milestone 1 Retrospective
  collaboration/retrospectives/1_problem_identification.md
Labels: documentation

#72 Adding problem statement
  README.md
Labels: documentation

#74 Background review
  0_domain_study/background_review.md
Labels: documentation

#76 Add review logs to planning documents
  collaboration/README.md
  collaboration/communication.md
  collaboration/constraints.md
  collaboration/learning_goals.md
Labels: documentation

#77 Few enhancements to Repository Readme
  README.md
Labels: enhancement

#78 Adding domain_study readme content
  0_domain_study/README.md
Labels: documentation

#81 fixed contributing.md link
  README.md
Labels: bug

#79 M1: Add initial research questions
  0_domain_study/research_notes/initial_research_questions.md
Labels: documentation

#82 fixed files links issues
  0_domain_study/README.md
Labels: bug

#87 Add Meeting Minutes #11 - Strategic Pivot & Milestone 2 Launch
  collaboration/meeting_minutes/milestone_2_06_19_meeting_11.md
Labels: documentation

#88 Add Meeting Minutes #12 -Data Source Exploration & Planning
  collaboration/meeting_minutes/milestone_2_06_23_meeting_12.md
Labels: documentation

#90 Preparation of 13th Meeting Minutes
  collaboration/meeting_minutes/milestone_2_06_23_meeting_13.md
Labels: documentation

#98 Tech EcoSystem & Feedback Channels Theme Datasets
  1_datasets/tech_ecosystem.md
Labels: documentation

#106 Add GIF to our approach
  README.md
Labels: enhancement

#104 Digital infrastructure datasets
  1_datasets/digital_infrastructure.md
Labels: documentation

#112 Add Barriers to Access datasets documentation
  1_datasets/barriers_to_access.md
Labels: documentation

#114 Add M2 Data Collection Retrospectives
  collaboration/retrospectives/2_data_collection.md
  collaboration/retrospectives/2_data_collection_group_retrospective.md
  collaboration/retrospectives/2_data_collection_individual_reflections.md
Labels: documentation

#116 Main README Minor Fixes
  README.md
Labels: enhancement
