Repository MIT-Emerging-Talent/ET6-CDSP-group-24-repo, pull requests merged in 2025-07, with the labels that each got.

#120 Meeting mins
  collaboration/meeting_minutes/milestone_3_07_03_meeting_15.md
Labels: documentation

#122 Add Meeting Minutes 16 – Milestone 3 (07/07)
  collaboration/meeting_minutes/milestone_3_07_07_meeting_16.md
Labels: documentation

#124 Add Meeting Minutes 17 – Milestone 3 (07/10)
  collaboration/meeting_minutes/milestone_3_07_10_meeting_17.md
Labels: documentation

#135 Add M3 Meeting Minutes #18 – Dataset Triage & Relevance Strategy
  collaboration/meeting_minutes/milestone_3_07_14_meeting_18.md
Labels: documentation

#142 Add irrelevant datasets
  1_datasets/README.md
  1_datasets/irrelevant_datasets.md
Labels: documentation

#147 Add datasets
  1_datasets/barriers_to_access/Access Denied _ Barriers to Access.pdf
  1_datasets/barriers_to_access/Accessibility to digital technology _ Barriers to Access.pdf
  1_datasets/barriers_to_access/Bridging the digital divide _ Barriers to Access.pdf
  1_datasets/barriers_to_access/ICT and Disability _ Barriers to Access.pdf
  1_datasets/barriers_to_access/Mobile Disability Gap Report 2021 _ Barriers to Access.pdf
  1_datasets/barriers_to_access/README.md
  1_datasets/barriers_to_access/Social protection and access to assistive technolo _ Barriers to Access.pdf
  1_datasets/barriers_to_access/Strengthening ICT Accessibility for PWDs in Africa _ Barriers to Access.pdf
  1_datasets/barriers_to_access/The Millions of Nigerians Whose Use of Technology is an Afterthought _ Barriers to Access.pdf
  1_datasets/barriers_to_access/The State of Digital Inclusion in Africa _ Barriers to Access.pdf
  1_datasets/case_studies/Akinola Opeolu _ Case Studies.pdf
  1_datasets/case_studies/Farida Bedwei _ Case Studies.pdf
  1_datasets/case_studies/Fredrick Ouko _ Case Studies.pdf
  1_datasets/case_studies/Innovating Inclusion _ Case Studies.pdf
  1_datasets/case_studies/Nafisa Baboo _ Case Studies.pdf
  1_datasets/case_studies/Papi Sibomana _ Case Studies.pdf
  1_datasets/case_studies/README.md
  1_datasets/digital_infrastructure/README.md
  1_datasets/inclusive_digital_technology/AI Assistive Technologies for Persons with Disabilities in Africa _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/AI for Inclusive Development in Africa (AT2030 Report) _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/Accessibility and Digital Inclusion Knowledge Document _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/Digital Inclusion Practices & Technology Accessibility in Nairobi _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/Disability Is Not Inability _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/Empowering PWD through Digital Innovation _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/How Can AI Assist African Disabled To Be Business Owners and Entrepreneurs _ Inclusive Digital Technology.pdf
  1_datasets/inclusive_digital_technology/README.md
  1_datasets/inclusive_digital_technology/Usability and Digital Accessibility Reports _ Inclusive Digital Technology.pdf
  1_datasets/tech_ecosystem/Best Practices in the Employment of Persons with Intellectual Disabilities _ Tech Ecosystem.pdf
  1_datasets/tech_ecosystem/Empowering Vulnerable Communities _ Tech Ecosystem.pdf
  1_datasets/tech_ecosystem/Inside Opeoluwa Akinola’s mission to empower PWD _ Tech Ecosystem.pdf
  1_datasets/tech_ecosystem/README.md
  1_datasets/tech_ecosystem/Safaricom PLC Disability Inclusion _ Tech Ecosystem.pdf
  1_datasets/tech_ecosystem/Sightsavers Inclusive Data 2024 Annual Review _ Tech Ecosystem.pdf
Labels: documentation

#170 Add Notebook for Top Keywords Per Theme and the CSV File
  1_datasets/processed_data/per_theme_top_keywords.csv
  3_data_exploration/top_keywords_per_theme.ipynb
Labels: notebooks

#175 Data Analysis Readme
  4_data_analysis/README.md
Labels: documentation

#171 Topic Modeling Analysis Notebook
  4_data_analysis/Topic_Modeling.ipynb
Labels: notebooks

#178 Add M3D2 Manual Coding Technical Description
  4_data_analysis/manual_analysis_technical_description.md
Labels: documentation

#184 Manual coding summary
  4_data_analysis/README.md
Labels: documentation

#185 Doc: Add M3 Data Analysis Retrospectives
  collaboration/retrospectives/3_data_analysis.md
  collaboration/retrospectives/3_data_analysis_group_retrospective.md
  collaboration/retrospectives/3_data_analysis_individual_reflections.md
Labels: documentation

#187 Update Main readme
  README.md
Labels: documentation

#188 Minor fixes in individual retro file
  collaboration/retrospectives/3_data_analysis_individual_reflections.md
Labels: documentation

#189 Enhance README
  README.md
Labels: enhancement

#194 Dataset readme
  1_datasets/README.md
  3_data_exploration/README.md
Labels: documentation, enhancement

#195 Data Analysis Readme - Better Quality and Structure for Visuals
  4_data_analysis/README.md
  4_data_analysis/Visual_01.jpg
  4_data_analysis/Visual_02.jpg
  4_data_analysis/Visual_03.jpg
  4_data_analysis/Visual_04.jpg
  4_data_analysis/visuals/2d_topic_space.jpg
  4_data_analysis/visuals/hierarchical_clustering.jpg
  4_data_analysis/visuals/similarity_matrix.jpg
  4_data_analysis/visuals/topic_word_scores.jpg
Labels: enhancement

#200 Fixing Keywords Extraction process and Adding Correct CSV file
  1_datasets/processed_data/per_theme_top_keywords.csv
  3_data_exploration/top_keywords_per_theme.ipynb
Labels: bug

#206 Refactor: Update README and docs formatting - Cleanup
  .markdownlint.yml
  0_domain_study/README.md
  0_domain_study/background_review.md
  0_domain_study/problem_statement.md
  0_domain_study/research_notes/initial_research_questions.md
  0_domain_study/research_notes/literature_review/jola.md
  0_domain_study/research_notes/literature_review/karim.md
  0_domain_study/research_notes/literature_review/muqadsa.md
  0_domain_study/research_notes/literature_review/omer.md
  0_domain_study/research_notes/literature_review/omnia.md
  0_domain_study/research_notes/literature_review/robel.md
  1_datasets/README.md
  1_datasets/barriers_to_access/README.md
  1_datasets/case_studies/README.md
  1_datasets/digital_infrastructure/README.md
  1_datasets/inclusive_digital_technology/README.md
  1_datasets/modeling_approach.md
  1_datasets/tech_ecosystem/README.md
  2_data_preparation/README.md
  4_data_analysis/README.md
  README.md
  collaboration/README.md
  collaboration/communication.md
  collaboration/constraints.md
  collaboration/meeting_minutes/milestone_1_06_14_meeting_09.md
  collaboration/meeting_minutes/milestone_1_06_16_meeting_10.md
  collaboration/meeting_minutes/milestone_2_06_23_meeting_13.md
  collaboration/meeting_minutes/milestone_3_07_07_meeting_16.md
  collaboration/meeting_minutes/milestone_3_07_10_meeting_17.md
  collaboration/meeting_minutes/milestone_4_07_24_meeting_19.md
  collaboration/retrospectives/2_data_collection_individual_reflections.md
  collaboration/retrospectives/3_data_analysis_group_retrospective.md
  collaboration/retrospectives/3_data_analysis_individual_reflections.md
  collaboration/retrospectives/README.md
  collaboration/retrospectives/_template.md
Labels: enhancement

#210 Update Team logo
  README.md
Labels: documentation

#213 Refactor: Updated READMEs for clarity and integrated findings.
  4_data_analysis/README.md
  4_data_analysis/mixed_methods_findings.md
  README.md
Labels: documentation, enhancement
