Repository MIT-Emerging-Talent/ET6-CDSP-group-24-repo, pull requests merged in 2025-08, with the labels that each got.

#218 Add meeting minutes for August 1 planning discussion
  collaboration/meeting_minutes/milestone_4_08_01_meeting_22.md
Labels: documentation

#220 Add meeting 22 minutes
  collaboration/meeting_minutes/milestone_4_08_04_meeting_22.md
Labels: meeting-agenda

#222 Preparing Meeting minutes #24
  collaboration/meeting_minutes/milestone_4_08_04_meeting_23.md
  collaboration/meeting_minutes/milestone_4_08_06_meeting_24.md
Labels: documentation

#233 Add Milestone 4 Communicating Results retrospective (group & individual)
  collaboration/retrospectives/4_communicating_results.md
  collaboration/retrospectives/4_communicating_results_group_retrospective.md
  collaboration/retrospectives/4_communicating_results_individual_reflections.md
  collaboration/retrospectives/README.md
Labels: documentation

#236 Preparing the Main readme file for Communications Milestone
  README.md
Labels: documentation

#241 Target Audience Personas Documentation
  5_communication_strategy/target_audience.md
Labels: documentation

#243 Add Outreach Templates And Stakeholder Profiles Documentation
  5_communication_strategy/email_outreach.md
Labels: documentation

#246 feat(recommendations): Add targeted recommendations document
  5_communication_strategy/targeted_recommendations.md
  README.md
Labels: documentation, communication

#249 Enhancement -Findings
  1_datasets/manual_coding.csv
  3_data_exploration/manual_coding.ipynb
  4_data_analysis/README.md
  4_data_analysis/manual_analysis_insights.md
  4_data_analysis/mixed_methods_findings.md
  4_data_analysis/visuals/manual_access_barriers.png
  4_data_analysis/visuals/manual_codes_cooccurrence.png
  4_data_analysis/visuals/manual_codes_distribution.png
  4_data_analysis/visuals/manual_digital_tech.png
  4_data_analysis/visuals/manual_inclusive_ecosystem.png
  4_data_analysis/visuals/manual_skills_gap.png
  4_data_analysis/visuals/manual_social_systemic.png
Labels: documentation, enhancement

#258 Final folder readme
  6_final_presentation/README.md
Labels: documentation

#260 preparing the presentation script
  6_final_presentation/presentation_script.md
Labels: documentation

#261 Fixing broken links
  6_final_presentation/README.md
Labels: bug
